name: msrv

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  msrv:
    runs-on: ubuntu-lastest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get Minimal Support Rust Version
        id: msrv
        run: |
          msrv=$(grep 'rust-version' Cargo.toml | sed 's/rust-version = "\([0-9\.]*\)"/\1/'
          echo "version=$msrv" >> "$GITHUB_OUTPUT"
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ steps.msrv.output.version }}
      - name: Check readme
        run: grep '${{ steps.msrv.output.version }}' Readme.md
      - name: Run tests
        run: cargo test --all-features
